### ISSUE TITLE
hook onUserChannel() not called?

### ISSUE THREAD

**Issue by hbeni** [bkacjios/lua-mumble#15]
Hi,
i try to use the following hook from the readme to detect users joining my channel:

```lua
client:hook("OnUserChannel", function(event)
	--["user"]	= mumble.user user,
	--["actor"]	= mumble.user actor,
	--["from"]	= mumble.channel from,
	--["to"]	= mumble.channel to,
    print("OnUserChannel(): client joined channel: ", event.user.getName())
end)
```

However it never seems to fire?

I was curious and looked in the hooks example code, there the hook is missing.
Is it not implemented yet?

**Comment by bkacjios** [comment]
![OnUserChannel](https://i.imgur.com/qTtMDfc.png)

It appears to be working fine for me!

**Comment by hbeni** [comment]
Confirmed, now working as expected.
Don't know what was wrong, but i tried it several times and i even made an `os.exit(1)` trap that didn't fire...

Thanks for responding so fast (and sorry for the inconvinience!)
