### ISSUE TITLE
uninitialized error variable in client_play()

### ISSUE THREAD

**Issue by dmz1** [bkacjios/lua-mumble#17]
Hi,

It seems that error variable in client_play() (client.c) is not initialized and stb_vorbis_open_filename() in case of success does not change its value so that following error checking if statement works only by chance (on my setup it didn't work).

Simple solution:
```
-	int error;
+	int error = VORBIS__no_error;
```
Additionally I think there is possible memory leak in case of error in stb_vorbis_open_filename() - function returns without freeing the `sound` pointer.

**Comment by bkacjios** [comment]
Thanks for the reports! The sound pointer gets freed when the audio has finished playing.

https://github.com/bkacjios/lua-mumble/blob/master/audio.c#L135

**Comment by dmz1** [comment]
No problem, thank you for your library. 

With the leak I meant there is no free() corresponding to malloc() when stb_vorbis_open_filename() signals error:

Here is return:
https://github.com/bkacjios/lua-mumble/blob/master/client.c#L253

But here sound is assigned to client where it can be freed:
https://github.com/bkacjios/lua-mumble/blob/master/client.c#L264

Now I just looked at line you pointed but there is still no free for the sound itself (which is malloc'ed) - you only close the ogg.

**Comment by bkacjios** [comment]
Aha, I see. Thanks. I believe I fixed this. The sound object should be freed when the audio stops playing now. I also made it so it will properly stop/free any audio that is playing if the client disconnects partway through.
