### ISSUE TITLE
Hook:OnMessage

### ISSUE THREAD

**Issue by hbeni** [bkacjios/lua-mumble#20]
I just tried to implement a chat interface, based on received messages: https://github.com/bkacjios/lua-mumble#onmessage-mumbleclient-client-table-event

However, it seems that just the message gets set into the event table. users is always an empty table and actor `nil`:

```lua
client:hook("OnMessage", function(client, event)
    -- ["actor"]		= mumble.user actor,
    -- ["message"]		= String message,
    -- ["users"]		= Table users,
    -- ["channels"]	= Table channels
    print("OnMessage:client", client)
    pprint(client)
    print("OnMessage:event", event)
    pprint(event)
end)
```

Sending "test" in direct chat prints:
```
OnMessage:client        mumble.client: 0x41d3a428

OnMessage:event table: 0x41d39c08
{ 
  message = 'TEST',
  users = {} 
}
```

**Comment by hbeni** [comment]
Nevermind: The values are set somehow...

```lua
  print("message from user:"..client.me:getName())
  print("message from actor:"..event.actor:getName())
```
```
message from user:FGCOM-RADIO-59279
message from actor:251
```

**Comment by bkacjios** [comment]
I think the `users` and `channels` variables are only set when selecting multiple people to send a message to. Not sure if these values are actually passed to the bot though, to be honest.

**Comment by hbeni** [comment]
Thank you!
I wonder if there is any procedure to detect if the message is a channelmessage or usermessage?

**Comment by bkacjios** [comment]
After some testing, event.channels is set when it's not a direct message. You could use that to detect.

**Comment by hbeni** [comment]
Works like a charm!

You really should consider to document that somewhere, maybe https://github.com/bkacjios/lua-mumble/compare/master...hbeni:patch-1
