### ISSUE TITLE
Disconnect after receiving image

### ISSUE THREAD

**Issue by duarm** [bkacjios/lua-mumble#24]
Sending an image results in the bot disconnecting
```
OnDisconnect	garbage collected
```

**Comment by bkacjios** [comment]
Can you clarify what you mean? Sending an image through a message? Comment? Icon?

**Comment by duarm** [comment]
Sorry for the lack of information, The bot connects, and everything works well, if I send an image through mumble chat (using the official client), the bot disconnects. I'm running the hooks.lua example. Tried both png and jpgs of different sizes, both from disk, clipboard and drag & drop. I think the bot receives the image and fails somehow while decoding it.

Built myself from source, I'm on arch.
protobuf-c 1.5.0-2
libev 4.33-2

![2024-05-05_16:53:30](https://github.com/bkacjios/lua-mumble/assets/26150581/ebd1e561-6536-4bc7-8a20-b3a12883ce2a)

**Comment by bkacjios** [comment]
Ohhhhh. Interesting. I had no idea you could do that. Thanks! I'll look into it!

**Comment by bkacjios** [comment]
I wasn't able to reproduce this.. I dragged a picture to my mumble client, it sent, and the bot didn't seem to care. What's weird is the bot never received an OnMessage event at all.

**Comment by duarm** [comment]
I'll try to narrow down the problem this weekend. I'm on mumble 1.5.629-1

**Comment by bkacjios** [comment]
That might be the issue. 1.5 has a new protocol that I'm still working on.

**Comment by duarm** [comment]
> I wasn't able to reproduce this.. I dragged a picture to my mumble client, it sent, and the bot didn't seem to care. What's weird is the bot never received an OnMessage event at all.

Tested the async-connect branch and this is the behaviour I'm getting now.

**Comment by bkacjios** [comment]
I think this is fixed now with my latest merge into master. It now properly handles very large messages. You should get OnMessage event with the image data now.
