### ISSUE TITLE
Typo in README.md (mumble.user:isMuted()) and non-working mumble.user:isSelfMute()

### ISSUE THREAD

**Issue by Phazeus** [bkacjios/lua-mumble#8]
Hello!
I found a typo in README.md:
```
-- Returns if the user is muted or not
Boolean muted = mumble.user:isMuted()
```
But it is should be:
```
-- Returns if the user is muted or not
Boolean muted = mumble.user:isMute()
```
(isMute() works)
Also the function mumble.user:isSelfMute() does not works (seems to be always false).
Thanks.

**Comment by bkacjios** [comment]
isSelfMute seems to be working for me!

```lua
client:hook("OnUserState", function(event)
	print("OnUserState", event)

	print(event.user:isSelfMute())
end)
```

![selfMute](https://i.imgur.com/UH4ImrX.png)

But I added some aliases to the muted function in b4fb9ef255482fd086445f369ae80fc146ca2e85. You can now do isMute or isMuted, etc.

**Comment by Phazeus** [comment]
Ah yes, it works!
