### ISSUE TITLE
Add plugin packets

### ISSUE THREAD

**Issue by hbeni** [bkacjios/lua-mumble#9]
Hello,
https://github.com/mumble-voip/mumble/pull/3743 will introduce a new plugin framework and with that comes a new packet type in the protocol that allows plugins to communicate to each other.
It would be nice if this packet would be supported in the lua client lib.
Plugins can use the method to send arbitary data to each other via the server.
A hook call when such data is incoming would be good, as well as an function to send such data to other clients (via the server).

The protobuf definition is [here](https://github.com/Krzmbrzl/mumble/blob/plugin-API/src/Mumble.proto):
```// Used to send plugin messages between clients
message PluginDataTransmission {
	// The session ID of the client this message was sent from
	optional uint32 senderSession = 1;
	// The session IDs of the clients that should receive this message
	repeated uint32 receiverSessions = 2 [packed = true];
	// The data that is sent
	optional bytes data = 3;
	// The ID of the sent data. This will be used by plugins to check whether they will
	// process it or not
	optional string dataID = 4;
}
```

**Comment by bkacjios** [comment]
I could add this pretty easily, but this feature isn't even merged yet. Unless you really need it because you're testing the feature, I would probably wait to implement this?

**Comment by hbeni** [comment]
No rush, ticket was meant as "when its released and when you get time".
It was mainly a reminder to raise your awareness :)

**Comment by hbeni** [comment]
Thank you very much!
but if thats "no rush", what is fast then? :smile:
